/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DiceRouteImport } from './routes/dice'
import { Route as ColorsRouteImport } from './routes/colors'
import { Route as AsciiRouteImport } from './routes/ascii'
import { Route as IndexRouteImport } from './routes/index'

const DiceRoute = DiceRouteImport.update({
  id: '/dice',
  path: '/dice',
  getParentRoute: () => rootRouteImport,
} as any)
const ColorsRoute = ColorsRouteImport.update({
  id: '/colors',
  path: '/colors',
  getParentRoute: () => rootRouteImport,
} as any)
const AsciiRoute = AsciiRouteImport.update({
  id: '/ascii',
  path: '/ascii',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ascii': typeof AsciiRoute
  '/colors': typeof ColorsRoute
  '/dice': typeof DiceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ascii': typeof AsciiRoute
  '/colors': typeof ColorsRoute
  '/dice': typeof DiceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ascii': typeof AsciiRoute
  '/colors': typeof ColorsRoute
  '/dice': typeof DiceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ascii' | '/colors' | '/dice'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ascii' | '/colors' | '/dice'
  id: '__root__' | '/' | '/ascii' | '/colors' | '/dice'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AsciiRoute: typeof AsciiRoute
  ColorsRoute: typeof ColorsRoute
  DiceRoute: typeof DiceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dice': {
      id: '/dice'
      path: '/dice'
      fullPath: '/dice'
      preLoaderRoute: typeof DiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colors': {
      id: '/colors'
      path: '/colors'
      fullPath: '/colors'
      preLoaderRoute: typeof ColorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ascii': {
      id: '/ascii'
      path: '/ascii'
      fullPath: '/ascii'
      preLoaderRoute: typeof AsciiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AsciiRoute: AsciiRoute,
  ColorsRoute: ColorsRoute,
  DiceRoute: DiceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
